name: SpawnBlocker
author: ThatGuyCalledJesse
description: Controls what mobs can spawn and what mobs can't spawn. You can edit these mobs from the config file in the server files (<server folder>/plugin/MobRemoval/config.yml)
website: github.com/thatguycalledjesse
version: '1.0'
main: com.jesse.mobremoval.MobRemoval
api-version: '1.20'
commands:
  spawnblocker:
    description: Controls the stopping of spawning mobs
    usage: /spawnblocker <boolean>
